package src.handler;

public enum TipoSolicitud {
    PERMISO_INASISTENCIA,
    CAMBIO_HORARIO,
    HOMOLOGACION_NOTA,
    CERTIFICADO_ESTUDIO,
    RECLAMO_ACADEMICO,
    BECA_ESPECIAL,
    EXPULSION_DISCIPLINARIA,
}
